name: Push hotfix tag to relevant docs branch
on:
  push:
    tags:
      - "*.*.*"

permissions:
  contents: write

jobs:
  update-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Merge from docs and create PR
        run: |
          current_tag="$(git describe --exact-match)"
          if [[ ${current_tag} = *.0 ]]; then
            echo "Minor release, not merging" >> $GITHUB_SUMMARY
            exit 0
          fi
          minor_version=$(git describe --always | awk --field-separator=. '{ print $1 "." $2 }')
          docs_branch="docs/${minor_version}"
          git switch -c "merge-to-docs/${minor_version}"
          git merge "origin/$docs_branch"
          git push --set-upstream origin
          gh pr create --title "docs(auto): merge $current_tag to $docs-branch" --base "${docs_branch}"


