name: Create hotfix and docs branches for a minor release
on:
  push:
    tags:
      - "*.*.0"

permissions:
  contents: write

jobs:
  create-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Create hotfix branch
        if: always()
        run: |
          minor_version=$(git describe --always | awk --field-separator=. '{ print $1 "." $2 }')
          git switch -c "hotfix/$minor_version"
          git push --set-upstream origin "hotfix/$minor_version"
      - name: Create docs branch
        if: always()
        run: |
          minor_version=$(git describe --always | awk --field-separator=. '{ print $1 "." $2 }')
          git switch -c "docs/$minor_version"
          git push --set-upstream origin "docs/$minor_version"

